fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
gentie: 151c661ff0ff41c18669a374d3f8f153
google_search: false ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 4c66f02c419b1b8b035290646cd20eaf
baidu_push: true
show_category_count: true # 是否显示分类文章总数
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
#  - page: rss
#    directory: atom.xml
#    icon: icon-rss

sitemap:
  path: sitemap.xml
baidusitemap:
path: baidusitemap.xml

url: http://weeklyweb.info

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 百度FEX
    url: http://fex.baidu.com/
  - title: 阿里巴巴UED
    url: http://www.aliued.com/
  - title: 搜车大无线团队博客
    url: http://f2e.souche.com/blog/
  - title: 美团前端团队博客
    url: http://fe.meituan.com/
timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 1.0.1
